package cn.itcast.yycg.domain.po;
// Generated 2016-5-28 14:35:22 by Hibernate Tools 4.0.0

/**
 * DwGysDq generated by hbm2java
 */
public class DwGysDq implements java.io.Serializable {

	private String areaId;
	private SysArea sysArea;
	private DwGys dwGys;
	private String vchar1;
	private String vchar2;
	private String vchar3;

	public DwGysDq() {
	}

	

	public String getAreaId() {
		return this.areaId;
	}

	public void setAreaId(String areaId) {
		this.areaId = areaId;
	}

	public SysArea getSysArea() {
		return this.sysArea;
	}

	public void setSysArea(SysArea sysArea) {
		this.sysArea = sysArea;
	}

	

	public DwGys getDwGys() {
		return dwGys;
	}



	public void setDwGys(DwGys dwGys) {
		this.dwGys = dwGys;
	}



	public String getVchar1() {
		return this.vchar1;
	}

	public void setVchar1(String vchar1) {
		this.vchar1 = vchar1;
	}

	public String getVchar2() {
		return this.vchar2;
	}

	public void setVchar2(String vchar2) {
		this.vchar2 = vchar2;
	}

	public String getVchar3() {
		return this.vchar3;
	}

	public void setVchar3(String vchar3) {
		this.vchar3 = vchar3;
	}

}
