package cn.itcast.yycg.domain.po;
// Generated 2016-5-28 14:35:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * DwWss generated by hbm2java
 */
public class DwWss implements java.io.Serializable {

	private String id;
	private String mc;
	private String dz;
	private String yzbm;
	private SysArea sysArea;
	private String jb;
	private String cws;
	private String fyljg;
	private String dh;
	private String yjkdh;
	private String lb;
	private String ypsr;
	private String ywsr;
	private String cz;
	private String vchar1;
	private String vchar2;
	private String vchar3;
//	private Set sysUsers = new HashSet(0);

	public DwWss() {
	}

	public DwWss(String id, String mc) {
		this.id = id;
		this.mc = mc;
	}

	

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getMc() {
		return this.mc;
	}

	public void setMc(String mc) {
		this.mc = mc;
	}

	public String getDz() {
		return this.dz;
	}

	public void setDz(String dz) {
		this.dz = dz;
	}

	public String getYzbm() {
		return this.yzbm;
	}

	public void setYzbm(String yzbm) {
		this.yzbm = yzbm;
	}


	public SysArea getSysArea() {
		return sysArea;
	}

	public void setSysArea(SysArea sysArea) {
		this.sysArea = sysArea;
	}

	public String getJb() {
		return this.jb;
	}

	public void setJb(String jb) {
		this.jb = jb;
	}

	public String getCws() {
		return this.cws;
	}

	public void setCws(String cws) {
		this.cws = cws;
	}

	public String getFyljg() {
		return this.fyljg;
	}

	public void setFyljg(String fyljg) {
		this.fyljg = fyljg;
	}

	public String getDh() {
		return this.dh;
	}

	public void setDh(String dh) {
		this.dh = dh;
	}

	public String getYjkdh() {
		return this.yjkdh;
	}

	public void setYjkdh(String yjkdh) {
		this.yjkdh = yjkdh;
	}

	public String getLb() {
		return this.lb;
	}

	public void setLb(String lb) {
		this.lb = lb;
	}

	public String getYpsr() {
		return this.ypsr;
	}

	public void setYpsr(String ypsr) {
		this.ypsr = ypsr;
	}

	public String getYwsr() {
		return this.ywsr;
	}

	public void setYwsr(String ywsr) {
		this.ywsr = ywsr;
	}

	public String getCz() {
		return this.cz;
	}

	public void setCz(String cz) {
		this.cz = cz;
	}

	public String getVchar1() {
		return this.vchar1;
	}

	public void setVchar1(String vchar1) {
		this.vchar1 = vchar1;
	}

	public String getVchar2() {
		return this.vchar2;
	}

	public void setVchar2(String vchar2) {
		this.vchar2 = vchar2;
	}

	public String getVchar3() {
		return this.vchar3;
	}

	public void setVchar3(String vchar3) {
		this.vchar3 = vchar3;
	}

	/*public Set getSysUsers() {
		return this.sysUsers;
	}

	public void setSysUsers(Set sysUsers) {
		this.sysUsers = sysUsers;
	}*/

}
