package cn.itcast.yycg.domain.po;
// Generated 2016-5-28 14:35:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * SysDictInfo generated by hbm2java
 */
public class SysDictInfo implements java.io.Serializable {

	private String id;
	private SysDictType sysDictType;
	private String dictcode;
	private String info;
	private String remark;
	private String updatetime;
	private Integer dictsort;
	private String isenable;
	private String valuetype;
//	private Set ypxxesForLb = new HashSet(0);
//	private Set ypxxesForJyzt = new HashSet(0);
//	private Set yycgds = new HashSet(0);
//	private Set sysUsersForGroupid = new HashSet(0);
//	private Set yycgdMxes = new HashSet(0);
//	private Set sysUsersForUserstate = new HashSet(0);
//	private Set tjJymxes = new HashSet(0);
//	private Set sysRoles = new HashSet(0);

	public SysDictInfo() {
	}

	public SysDictInfo(String id, SysDictType sysDictType, String info, String isenable) {
		this.id = id;
		this.sysDictType = sysDictType;
		this.info = info;
		this.isenable = isenable;
	}

	

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public SysDictType getSysDictType() {
		return this.sysDictType;
	}

	public void setSysDictType(SysDictType sysDictType) {
		this.sysDictType = sysDictType;
	}

	public String getDictcode() {
		return this.dictcode;
	}

	public void setDictcode(String dictcode) {
		this.dictcode = dictcode;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(String updatetime) {
		this.updatetime = updatetime;
	}

	public Integer getDictsort() {
		return this.dictsort;
	}

	public void setDictsort(Integer dictsort) {
		this.dictsort = dictsort;
	}

	public String getIsenable() {
		return this.isenable;
	}

	public void setIsenable(String isenable) {
		this.isenable = isenable;
	}

	public String getValuetype() {
		return this.valuetype;
	}

	public void setValuetype(String valuetype) {
		this.valuetype = valuetype;
	}

	/*public Set getYpxxesForLb() {
		return this.ypxxesForLb;
	}

	public void setYpxxesForLb(Set ypxxesForLb) {
		this.ypxxesForLb = ypxxesForLb;
	}

	public Set getYpxxesForJyzt() {
		return this.ypxxesForJyzt;
	}

	public void setYpxxesForJyzt(Set ypxxesForJyzt) {
		this.ypxxesForJyzt = ypxxesForJyzt;
	}

	public Set getYycgds() {
		return this.yycgds;
	}

	public void setYycgds(Set yycgds) {
		this.yycgds = yycgds;
	}

	public Set getSysUsersForGroupid() {
		return this.sysUsersForGroupid;
	}

	public void setSysUsersForGroupid(Set sysUsersForGroupid) {
		this.sysUsersForGroupid = sysUsersForGroupid;
	}

	public Set getYycgdMxes() {
		return this.yycgdMxes;
	}

	public void setYycgdMxes(Set yycgdMxes) {
		this.yycgdMxes = yycgdMxes;
	}

	public Set getSysUsersForUserstate() {
		return this.sysUsersForUserstate;
	}

	public void setSysUsersForUserstate(Set sysUsersForUserstate) {
		this.sysUsersForUserstate = sysUsersForUserstate;
	}

	public Set getTjJymxes() {
		return this.tjJymxes;
	}

	public void setTjJymxes(Set tjJymxes) {
		this.tjJymxes = tjJymxes;
	}

	public Set getSysRoles() {
		return this.sysRoles;
	}

	public void setSysRoles(Set sysRoles) {
		this.sysRoles = sysRoles;
	}*/

}
