package cn.itcast.yycg.domain.po;
// Generated 2016-5-28 14:35:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * SysDictType generated by hbm2java
 */
public class SysDictType implements java.io.Serializable {

	private String typecode;
	private String typename;
	private String remark;
	private Integer typesort;
	private Integer codelength;
//	private Set sysDictInfos = new HashSet(0);

	public SysDictType() {
	}

	public SysDictType(String typecode, String typename) {
		this.typecode = typecode;
		this.typename = typename;
	}

	

	public String getTypecode() {
		return this.typecode;
	}

	public void setTypecode(String typecode) {
		this.typecode = typecode;
	}

	public String getTypename() {
		return this.typename;
	}

	public void setTypename(String typename) {
		this.typename = typename;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getTypesort() {
		return this.typesort;
	}

	public void setTypesort(Integer typesort) {
		this.typesort = typesort;
	}

	public Integer getCodelength() {
		return this.codelength;
	}

	public void setCodelength(Integer codelength) {
		this.codelength = codelength;
	}

	/*public Set getSysDictInfos() {
		return this.sysDictInfos;
	}

	public void setSysDictInfos(Set sysDictInfos) {
		this.sysDictInfos = sysDictInfos;
	}*/

}
