package cn.itcast.yycg.domain.po;
// Generated 2016-5-28 14:35:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import com.alibaba.fastjson.annotation.JSONField;

/**
 * SysPermission generated by hbm2java
 */
public class SysPermission implements java.io.Serializable {

	private String id;
	private String name;
	private String parentid;
	private String url;
	private String icon;
	private String showorder;
	private String isused;
	private String ismenu;
	private String plevel;
	private String pcode;
	private String vchar1;
	@JSONField(serialize=false)
	private Set sysRoles = new HashSet(0);

	public SysPermission() {
	}

	public SysPermission(String id, String name, String parentid, String isused) {
		this.id = id;
		this.name = name;
		this.parentid = parentid;
		this.isused = isused;
	}

	public SysPermission(String id, String name, String parentid, String url, String icon, String showorder,
			String isused, String ismenu, String plevel, String pcode, String vchar1, Set sysRoles) {
		this.id = id;
		this.name = name;
		this.parentid = parentid;
		this.url = url;
		this.icon = icon;
		this.showorder = showorder;
		this.isused = isused;
		this.ismenu = ismenu;
		this.plevel = plevel;
		this.pcode = pcode;
		this.vchar1 = vchar1;
		this.sysRoles = sysRoles;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getParentid() {
		return this.parentid;
	}

	public void setParentid(String parentid) {
		this.parentid = parentid;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public String getShoworder() {
		return this.showorder;
	}

	public void setShoworder(String showorder) {
		this.showorder = showorder;
	}

	public String getIsused() {
		return this.isused;
	}

	public void setIsused(String isused) {
		this.isused = isused;
	}

	public String getIsmenu() {
		return this.ismenu;
	}

	public void setIsmenu(String ismenu) {
		this.ismenu = ismenu;
	}

	public String getPlevel() {
		return this.plevel;
	}

	public void setPlevel(String plevel) {
		this.plevel = plevel;
	}

	public String getPcode() {
		return this.pcode;
	}

	public void setPcode(String pcode) {
		this.pcode = pcode;
	}

	public String getVchar1() {
		return this.vchar1;
	}

	public void setVchar1(String vchar1) {
		this.vchar1 = vchar1;
	}

	public Set getSysRoles() {
		return this.sysRoles;
	}

	public void setSysRoles(Set sysRoles) {
		this.sysRoles = sysRoles;
	}

}
