package cn.itcast.yycg.domain.po;
// Generated 2016-5-28 14:35:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import com.alibaba.fastjson.annotation.JSONField;

/**
 * SysRole generated by hbm2java
 */
public class SysRole implements java.io.Serializable {

	private String id;
	private SysDictInfo sysDictInfo;
	private String name;
	private String vchar1;
	private String vchar2;
	private String vchar3;
//	private Set sysUsers = new HashSet(0);
	@JSONField(serialize=false)
	private Set sysPermissions = new HashSet(0);

	public SysRole() {
	}

	public SysRole(String id, SysDictInfo sysDictInfo, String name) {
		this.id = id;
		this.sysDictInfo = sysDictInfo;
		this.name = name;
	}

	
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public SysDictInfo getSysDictInfo() {
		return this.sysDictInfo;
	}

	public void setSysDictInfo(SysDictInfo sysDictInfo) {
		this.sysDictInfo = sysDictInfo;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getVchar1() {
		return this.vchar1;
	}

	public void setVchar1(String vchar1) {
		this.vchar1 = vchar1;
	}

	public String getVchar2() {
		return this.vchar2;
	}

	public void setVchar2(String vchar2) {
		this.vchar2 = vchar2;
	}

	public String getVchar3() {
		return this.vchar3;
	}

	public void setVchar3(String vchar3) {
		this.vchar3 = vchar3;
	}

/*	public Set getSysUsers() {
		return this.sysUsers;
	}

	public void setSysUsers(Set sysUsers) {
		this.sysUsers = sysUsers;
	}*/

	public Set getSysPermissions() {
		return this.sysPermissions;
	}

	public void setSysPermissions(Set sysPermissions) {
		this.sysPermissions = sysPermissions;
	}

}
