package cn.itcast.yycg.domain.po;
// Generated 2016-6-23 13:35:19 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * SysTask generated by hbm2java
 */
public class SysTask implements java.io.Serializable {

	private Long id;
	private String taskType;
	private String data1;
	private String data2;
	private String data3;
	private String data4;
	private String data5;
	private Date taskAddDate;

	public SysTask() {
	}

	public SysTask(Long id, String taskType) {
		this.id = id;
		this.taskType = taskType;
	}

	public SysTask(Long id, String taskType, String data1, String data2, String data3, String data4, String data5,
			Date taskAddDate) {
		this.id = id;
		this.taskType = taskType;
		this.data1 = data1;
		this.data2 = data2;
		this.data3 = data3;
		this.data4 = data4;
		this.data5 = data5;
		this.taskAddDate = taskAddDate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTaskType() {
		return this.taskType;
	}

	public void setTaskType(String taskType) {
		this.taskType = taskType;
	}

	public String getData1() {
		return this.data1;
	}

	public void setData1(String data1) {
		this.data1 = data1;
	}

	public String getData2() {
		return this.data2;
	}

	public void setData2(String data2) {
		this.data2 = data2;
	}

	public String getData3() {
		return this.data3;
	}

	public void setData3(String data3) {
		this.data3 = data3;
	}

	public String getData4() {
		return this.data4;
	}

	public void setData4(String data4) {
		this.data4 = data4;
	}

	public String getData5() {
		return this.data5;
	}

	public void setData5(String data5) {
		this.data5 = data5;
	}

	public Date getTaskAddDate() {
		return this.taskAddDate;
	}

	public void setTaskAddDate(Date taskAddDate) {
		this.taskAddDate = taskAddDate;
	}

}
