package cn.itcast.yycg.domain.po;
// Generated 2016-5-28 14:35:22 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Ypxx generated by hbm2java
 */
public class Ypxx implements java.io.Serializable {

	private String id;
	private SysDictInfo sysDictInfoByJyzt;
	private SysDictInfo sysDictInfoByLb;
	private String bm;
	private String scqymc;
	private String spmc;
	private Float zbjg;
	private String zpdz;
	private String pzwh;
	private Date pzwhyxq;
	private String jky;
	private String bzcz;
	private String bzdw;
	private Float lsjg;
	private String lsjgcc;
	private String zlcc;
	private String zlccsm;
	private String ypjybg;
	private String ypjybgbm;
	private Date ypjybgyxq;
	private String cpsm;
	private String vchar1;
	private String vchar2;
	private String vchar3;
	private String dw;
	private String mc;
	private String jx;
	private String gg;
	private String zhxs;
	private String py;
	private String sj;

	public Ypxx() {
	}

	public Ypxx(String id, SysDictInfo sysDictInfoByJyzt, String bm, String scqymc, String spmc, Float zbjg, String dw,
			String mc, String jx, String gg, String zhxs) {
		this.id = id;
		this.sysDictInfoByJyzt = sysDictInfoByJyzt;
		this.bm = bm;
		this.scqymc = scqymc;
		this.spmc = spmc;
		this.zbjg = zbjg;
		this.dw = dw;
		this.mc = mc;
		this.jx = jx;
		this.gg = gg;
		this.zhxs = zhxs;
	}

	public Ypxx(String id, SysDictInfo sysDictInfoByJyzt, SysDictInfo sysDictInfoByLb, String bm, String scqymc,
			String spmc, Float zbjg, String zpdz, String pzwh, Date pzwhyxq, String jky, String bzcz, String bzdw,
			Float lsjg, String lsjgcc, String zlcc, String zlccsm, String ypjybg, String ypjybgbm, Date ypjybgyxq,
			String cpsm, String vchar1, String vchar2, String vchar3, String dw, String mc, String jx, String gg,
			String zhxs, String py, String sj) {
		this.id = id;
		this.sysDictInfoByJyzt = sysDictInfoByJyzt;
		this.sysDictInfoByLb = sysDictInfoByLb;
		this.bm = bm;
		this.scqymc = scqymc;
		this.spmc = spmc;
		this.zbjg = zbjg;
		this.zpdz = zpdz;
		this.pzwh = pzwh;
		this.pzwhyxq = pzwhyxq;
		this.jky = jky;
		this.bzcz = bzcz;
		this.bzdw = bzdw;
		this.lsjg = lsjg;
		this.lsjgcc = lsjgcc;
		this.zlcc = zlcc;
		this.zlccsm = zlccsm;
		this.ypjybg = ypjybg;
		this.ypjybgbm = ypjybgbm;
		this.ypjybgyxq = ypjybgyxq;
		this.cpsm = cpsm;
		this.vchar1 = vchar1;
		this.vchar2 = vchar2;
		this.vchar3 = vchar3;
		this.dw = dw;
		this.mc = mc;
		this.jx = jx;
		this.gg = gg;
		this.zhxs = zhxs;
		this.py = py;
		this.sj = sj;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public SysDictInfo getSysDictInfoByJyzt() {
		return this.sysDictInfoByJyzt;
	}

	public void setSysDictInfoByJyzt(SysDictInfo sysDictInfoByJyzt) {
		this.sysDictInfoByJyzt = sysDictInfoByJyzt;
	}

	public SysDictInfo getSysDictInfoByLb() {
		return this.sysDictInfoByLb;
	}

	public void setSysDictInfoByLb(SysDictInfo sysDictInfoByLb) {
		this.sysDictInfoByLb = sysDictInfoByLb;
	}

	public String getBm() {
		return this.bm;
	}

	public void setBm(String bm) {
		this.bm = bm;
	}

	public String getScqymc() {
		return this.scqymc;
	}

	public void setScqymc(String scqymc) {
		this.scqymc = scqymc;
	}

	public String getSpmc() {
		return this.spmc;
	}

	public void setSpmc(String spmc) {
		this.spmc = spmc;
	}

	public Float getZbjg() {
		return this.zbjg;
	}

	public void setZbjg(Float zbjg) {
		this.zbjg = zbjg;
	}

	public String getZpdz() {
		return this.zpdz;
	}

	public void setZpdz(String zpdz) {
		this.zpdz = zpdz;
	}

	public String getPzwh() {
		return this.pzwh;
	}

	public void setPzwh(String pzwh) {
		this.pzwh = pzwh;
	}

	public Date getPzwhyxq() {
		return this.pzwhyxq;
	}

	public void setPzwhyxq(Date pzwhyxq) {
		this.pzwhyxq = pzwhyxq;
	}

	public String getJky() {
		return this.jky;
	}

	public void setJky(String jky) {
		this.jky = jky;
	}

	public String getBzcz() {
		return this.bzcz;
	}

	public void setBzcz(String bzcz) {
		this.bzcz = bzcz;
	}

	public String getBzdw() {
		return this.bzdw;
	}

	public void setBzdw(String bzdw) {
		this.bzdw = bzdw;
	}

	public Float getLsjg() {
		return this.lsjg;
	}

	public void setLsjg(Float lsjg) {
		this.lsjg = lsjg;
	}

	public String getLsjgcc() {
		return this.lsjgcc;
	}

	public void setLsjgcc(String lsjgcc) {
		this.lsjgcc = lsjgcc;
	}

	public String getZlcc() {
		return this.zlcc;
	}

	public void setZlcc(String zlcc) {
		this.zlcc = zlcc;
	}

	public String getZlccsm() {
		return this.zlccsm;
	}

	public void setZlccsm(String zlccsm) {
		this.zlccsm = zlccsm;
	}

	public String getYpjybg() {
		return this.ypjybg;
	}

	public void setYpjybg(String ypjybg) {
		this.ypjybg = ypjybg;
	}

	public String getYpjybgbm() {
		return this.ypjybgbm;
	}

	public void setYpjybgbm(String ypjybgbm) {
		this.ypjybgbm = ypjybgbm;
	}

	public Date getYpjybgyxq() {
		return this.ypjybgyxq;
	}

	public void setYpjybgyxq(Date ypjybgyxq) {
		this.ypjybgyxq = ypjybgyxq;
	}

	public String getCpsm() {
		return this.cpsm;
	}

	public void setCpsm(String cpsm) {
		this.cpsm = cpsm;
	}

	public String getVchar1() {
		return this.vchar1;
	}

	public void setVchar1(String vchar1) {
		this.vchar1 = vchar1;
	}

	public String getVchar2() {
		return this.vchar2;
	}

	public void setVchar2(String vchar2) {
		this.vchar2 = vchar2;
	}

	public String getVchar3() {
		return this.vchar3;
	}

	public void setVchar3(String vchar3) {
		this.vchar3 = vchar3;
	}

	public String getDw() {
		return this.dw;
	}

	public void setDw(String dw) {
		this.dw = dw;
	}

	public String getMc() {
		return this.mc;
	}

	public void setMc(String mc) {
		this.mc = mc;
	}

	public String getJx() {
		return this.jx;
	}

	public void setJx(String jx) {
		this.jx = jx;
	}

	public String getGg() {
		return this.gg;
	}

	public void setGg(String gg) {
		this.gg = gg;
	}

	public String getZhxs() {
		return this.zhxs;
	}

	public void setZhxs(String zhxs) {
		this.zhxs = zhxs;
	}

	public String getPy() {
		return this.py;
	}

	public void setPy(String py) {
		this.py = py;
	}

	public String getSj() {
		return this.sj;
	}

	public void setSj(String sj) {
		this.sj = sj;
	}

}
