package cn.itcast.yycg.domain.po;
// Generated 2016-6-21 19:38:06 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Yybusiness generated by hbm2java
 */
public class Yybusiness implements java.io.Serializable {

	private String id;
	private DwWss dwWss;
	private Ypxx ypxx;
	private DwGys dwGys;
	private SysDictInfo sysDictInfoByCgzt;
	private Yycgd yycgd;
	private Float zbjg;
	private Float jyjg;
	private Integer cgl;
	private Float cgje;
	private Integer rkl;
	private Float rkje;
	private String rkdh;
	private String ypph;
	private Float ypyxq;
	private Date rktime;
	private Date fhtime;
	private String yythdId;
	private Integer thl;
	private Float thje;
	private String thzt;
	private String thyy;
	private String yyjsdId;
	private Integer jsl;
	private Float jsje;
	private String jszt;
	private String vchar1;
	private String vchar2;
	private String vchar3;
	private Date tjsj;

	public Yybusiness() {
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public DwWss getDwWss() {
		return this.dwWss;
	}

	public void setDwWss(DwWss dwWss) {
		this.dwWss = dwWss;
	}

	public Ypxx getYpxx() {
		return this.ypxx;
	}

	public void setYpxx(Ypxx ypxx) {
		this.ypxx = ypxx;
	}

	public DwGys getDwGys() {
		return this.dwGys;
	}

	public void setDwGys(DwGys dwGys) {
		this.dwGys = dwGys;
	}

	public SysDictInfo getSysDictInfoByCgzt() {
		return sysDictInfoByCgzt;
	}

	public void setSysDictInfoByCgzt(SysDictInfo sysDictInfoByCgzt) {
		this.sysDictInfoByCgzt = sysDictInfoByCgzt;
	}

	public Yycgd getYycgd() {
		return this.yycgd;
	}

	public void setYycgd(Yycgd yycgd) {
		this.yycgd = yycgd;
	}

	public Float getZbjg() {
		return this.zbjg;
	}

	public void setZbjg(Float zbjg) {
		this.zbjg = zbjg;
	}

	public Float getJyjg() {
		return this.jyjg;
	}

	public void setJyjg(Float jyjg) {
		this.jyjg = jyjg;
	}

	public Integer getCgl() {
		return this.cgl;
	}

	public void setCgl(Integer cgl) {
		this.cgl = cgl;
	}

	public Float getCgje() {
		return this.cgje;
	}

	public void setCgje(Float cgje) {
		this.cgje = cgje;
	}

	public Integer getRkl() {
		return this.rkl;
	}

	public void setRkl(Integer rkl) {
		this.rkl = rkl;
	}

	public Float getRkje() {
		return this.rkje;
	}

	public void setRkje(Float rkje) {
		this.rkje = rkje;
	}

	public String getRkdh() {
		return this.rkdh;
	}

	public void setRkdh(String rkdh) {
		this.rkdh = rkdh;
	}

	public String getYpph() {
		return this.ypph;
	}

	public void setYpph(String ypph) {
		this.ypph = ypph;
	}

	public Float getYpyxq() {
		return this.ypyxq;
	}

	public void setYpyxq(Float ypyxq) {
		this.ypyxq = ypyxq;
	}

	public Date getRktime() {
		return this.rktime;
	}

	public void setRktime(Date rktime) {
		this.rktime = rktime;
	}

	public Date getFhtime() {
		return this.fhtime;
	}

	public void setFhtime(Date fhtime) {
		this.fhtime = fhtime;
	}

	public String getYythdId() {
		return this.yythdId;
	}

	public void setYythdId(String yythdId) {
		this.yythdId = yythdId;
	}

	public Integer getThl() {
		return this.thl;
	}

	public void setThl(Integer thl) {
		this.thl = thl;
	}

	public Float getThje() {
		return this.thje;
	}

	public void setThje(Float thje) {
		this.thje = thje;
	}

	public String getThzt() {
		return this.thzt;
	}

	public void setThzt(String thzt) {
		this.thzt = thzt;
	}

	public String getThyy() {
		return this.thyy;
	}

	public void setThyy(String thyy) {
		this.thyy = thyy;
	}

	public String getYyjsdId() {
		return this.yyjsdId;
	}

	public void setYyjsdId(String yyjsdId) {
		this.yyjsdId = yyjsdId;
	}

	public Integer getJsl() {
		return this.jsl;
	}

	public void setJsl(Integer jsl) {
		this.jsl = jsl;
	}

	public Float getJsje() {
		return this.jsje;
	}

	public void setJsje(Float jsje) {
		this.jsje = jsje;
	}

	public String getJszt() {
		return this.jszt;
	}

	public void setJszt(String jszt) {
		this.jszt = jszt;
	}

	public String getVchar1() {
		return this.vchar1;
	}

	public void setVchar1(String vchar1) {
		this.vchar1 = vchar1;
	}

	public String getVchar2() {
		return this.vchar2;
	}

	public void setVchar2(String vchar2) {
		this.vchar2 = vchar2;
	}

	public String getVchar3() {
		return this.vchar3;
	}

	public void setVchar3(String vchar3) {
		this.vchar3 = vchar3;
	}

	public Date getTjsj() {
		return this.tjsj;
	}

	public void setTjsj(Date tjsj) {
		this.tjsj = tjsj;
	}

}
