package cn.itcast.yycg.domain.po;
// Generated 2016-6-21 16:07:06 by Hibernate Tools 4.0.0

/**
 * YycgdMx generated by hbm2java
 */
public class YycgdMx implements java.io.Serializable {

	private String id;
	private Ypxx ypxx;
	private SysDictInfo sysDictInfoCgzt;
	private Yycgd yycgd;
	private Float zbjg;
	private Float jyjg;
	private Integer cgl;
	private Float cgje;
	private String vchar1;
	private String vchar2;
	private String vchar3;

	public YycgdMx() {
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Ypxx getYpxx() {
		return this.ypxx;
	}

	public void setYpxx(Ypxx ypxx) {
		this.ypxx = ypxx;
	}

	public SysDictInfo getSysDictInfoCgzt() {
		return sysDictInfoCgzt;
	}

	public void setSysDictInfoCgzt(SysDictInfo sysDictInfoCgzt) {
		this.sysDictInfoCgzt = sysDictInfoCgzt;
	}

	public Yycgd getYycgd() {
		return this.yycgd;
	}

	public void setYycgd(Yycgd yycgd) {
		this.yycgd = yycgd;
	}

	public Float getZbjg() {
		return this.zbjg;
	}

	public void setZbjg(Float zbjg) {
		this.zbjg = zbjg;
	}

	public Float getJyjg() {
		return this.jyjg;
	}

	public void setJyjg(Float jyjg) {
		this.jyjg = jyjg;
	}

	public Integer getCgl() {
		return this.cgl;
	}

	public void setCgl(Integer cgl) {
		this.cgl = cgl;
	}

	public Float getCgje() {
		return this.cgje;
	}

	public void setCgje(Float cgje) {
		this.cgje = cgje;
	}

	public String getVchar1() {
		return this.vchar1;
	}

	public void setVchar1(String vchar1) {
		this.vchar1 = vchar1;
	}

	public String getVchar2() {
		return this.vchar2;
	}

	public void setVchar2(String vchar2) {
		this.vchar2 = vchar2;
	}

	public String getVchar3() {
		return this.vchar3;
	}

	public void setVchar3(String vchar3) {
		this.vchar3 = vchar3;
	}

}
