package cn.itcast.yycg.domain.po;
// Generated 2016-6-21 16:07:06 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.alibaba.fastjson.annotation.JSONField;

/**
 * Yycgd generated by hbm2java
 */
public class Yycgd implements java.io.Serializable {

	private Integer id;
	private DwWss dwWss;
	private SysDictInfo sysDictInfoByzt;
	private DwGys dwGys;
	private String mc;
	private String lxr;
	private String lxdh;
	private String cjr;
	private Date cjsj;
	private Date tjsj;
	private String bz;
	private String shyj;
	private Date shsj;
	private String vchar1;
	private String vchar2;
	private Date xgsj;
	@JSONField(serialize=false)
	private Set yycgdMxes = new HashSet(0);

	public Yycgd() {
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public DwWss getDwWss() {
		return this.dwWss;
	}

	public void setDwWss(DwWss dwWss) {
		this.dwWss = dwWss;
	}

	public SysDictInfo getSysDictInfoByzt() {
		return sysDictInfoByzt;
	}

	public void setSysDictInfoByzt(SysDictInfo sysDictInfoByzt) {
		this.sysDictInfoByzt = sysDictInfoByzt;
	}

	public DwGys getDwGys() {
		return this.dwGys;
	}

	public void setDwGys(DwGys dwGys) {
		this.dwGys = dwGys;
	}

	public String getMc() {
		return this.mc;
	}

	public void setMc(String mc) {
		this.mc = mc;
	}

	public String getLxr() {
		return this.lxr;
	}

	public void setLxr(String lxr) {
		this.lxr = lxr;
	}

	public String getLxdh() {
		return this.lxdh;
	}

	public void setLxdh(String lxdh) {
		this.lxdh = lxdh;
	}

	public String getCjr() {
		return this.cjr;
	}

	public void setCjr(String cjr) {
		this.cjr = cjr;
	}

	public Date getCjsj() {
		return this.cjsj;
	}

	public void setCjsj(Date cjsj) {
		this.cjsj = cjsj;
	}

	public Date getTjsj() {
		return this.tjsj;
	}

	public void setTjsj(Date tjsj) {
		this.tjsj = tjsj;
	}

	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	public String getShyj() {
		return this.shyj;
	}

	public void setShyj(String shyj) {
		this.shyj = shyj;
	}

	public Date getShsj() {
		return this.shsj;
	}

	public void setShsj(Date shsj) {
		this.shsj = shsj;
	}

	public String getVchar1() {
		return this.vchar1;
	}

	public void setVchar1(String vchar1) {
		this.vchar1 = vchar1;
	}

	public String getVchar2() {
		return this.vchar2;
	}

	public void setVchar2(String vchar2) {
		this.vchar2 = vchar2;
	}

	public Date getXgsj() {
		return this.xgsj;
	}

	public void setXgsj(Date xgsj) {
		this.xgsj = xgsj;
	}

	public Set getYycgdMxes() {
		return this.yycgdMxes;
	}

	public void setYycgdMxes(Set yycgdMxes) {
		this.yycgdMxes = yycgdMxes;
	}

}
